http:
  routers:
    nextcloud:
      rule: "Host(`cloud.home.lucadibello.ch`)"
      entrypoints:
        - "websecure"
      service: nextcloud
      middlewares:
        - nextcloud-secure-headers
      tls:
        certresolver: "letsencrypt"

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud-aio-apache:11000"

  middlewares:
    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
