version: "3.9"

networks:
  traefik-network:
    external: true
  dns-network:
    external: true

volumes:
  adguard-workdir:
    driver: local
  adguard-confdir:
    driver: local

services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Zurich
    ports:
      - "${IP_ADDRESS}:53:53/tcp"
      - "${IP_ADDRESS}:53:53/udp"
    volumes:
      - ./bind9/config:/etc/bind/
      - ./bind9/cache:/var/cache/bind
      - ./bind9/records:/var/lib/bind
    restart: always
    networks:
      - dns-network
