version: "3.9"

networks:
  traefik-network:
    external: true

volumes:
  nextcloud_aio_mastercontainer:
    external: true

services:
  nextcloud:
    container_name: nextcloud-aio-mastercontainer
    restart: always
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - NEXTCLOUD_DATADIR=/mnt/nas-data
      - SKIP_DOMAIN_VALIDATION=true
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: "nextcloud/all-in-one:latest"
    ports:
      - 8080:8080
    networks:
      - traefik-network 
