version: '3'

volumes:
  keycloak-data:
    driver: local
  
networks:
  keycloak-network:
    external: true
  traefik-network:
    external: true
    
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.local.example.ch`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-network"
    command:
      - start
      - --import-realm
      - --hostname example-server
    networks:
      - keycloak-network
      - traefik-network
    volumes:
      - keycloak-data:/opt/keycloak/data/import